name: Shared - SwiftLint
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, edited, synchronize]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: SwiftLint
        run: |
          set -o pipefail
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            norionomura/swiftlint:0.59.1_swift-5.9.0 \
            swiftlint --reporter github-actions-logging --strict --quiet \
            | tee >(grep -oP 'file=[^,]+,line=\d+' \
            | sed -E 's/file=([^,]+),line=([0-9]+)/\1:\2/' >&2 || true)
