name: Update Code Signing Assets
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Code Signing target"
        type: choice
        required: true
        options:
           - ios-release-appstore
           - ios-release-adhoc
           - ios-alpha-appstore
           - ios-alpha-adhoc
           - macos-release-appstore
           - macos-release-dmg
           - macos-review-dmg
           - macos-ci

jobs:
  update_code_signing:
    runs-on: macos-15
    name: Update Code Signing Assets

    steps:

      - name: Register SSH keys for access to certificates
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Setup Ruby and dependencies for iOS
        if: startsWith(inputs.target, 'ios')
        uses: ./.github/actions/setup-ruby
        with:
          working-directory: iOS
          cache-key-prefix: ios-ruby

      - name: Setup Ruby and dependencies for macOS
        if: startsWith(inputs.target, 'macos')
        uses: ./.github/actions/setup-ruby
        with:
          working-directory: macOS
          cache-key-prefix: macos-ruby

      - name: Update code signing assets
        env:
          APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
          APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          case "${{ inputs.target }}" in
            ios-release-appstore)
              platform="iOS"
              lane="sync_signing"
              ;;
            ios-release-adhoc)
              platform="iOS"
              lane="sync_signing_adhoc"
              ;;
            ios-alpha-appstore)
              platform="iOS"
              lane="sync_signing_alpha"
              ;;
            ios-alpha-adhoc)
              platform="iOS"
              lane="sync_signing_alpha_adhoc"
              ;;
            macos-release-appstore)
              platform="macOS"
              lane="sync_signing"
              ;;
            macos-release-dmg)
              platform="macOS"
              lane="sync_signing_dmg_release"
              ;;
            macos-review-dmg)
              platform="macOS"
              lane="sync_signing_dmg_review"
              ;;
            macos-ci)
              platform="macOS"
              lane="sync_signing_ci"
              ;;
          esac
 
          cd "$platform"
          bundle exec fastlane ${lane}
